export const SITES_LOAD_REQUEST = 'SITES_LOAD_REQUEST'
export const SITES_LOAD_SUCCESS = 'SITES_LOAD_SUCCESS'
export const SITES_LOAD_FAIL = 'SITES_LOAD_FAIL'

export const PROFILE_LOAD_REQUEST = 'PROFILE_LOAD_REQUEST'
export const PROFILE_LOAD_SUCCESS = 'PROFILE_LOAD_SUCCESS'
export const PROFILE_LOAD_FAIL = 'PROFILE_LOAD_FAIL'
export const PROFILE_LOGOUT = 'PROFILE_LOGOUT'